import { computed, inject, Injectable } from '@angular/core';

import { LanguageCode, PublicI18nService } from './public-i18n.service';

export const APP_COPY = {
  fr: {
    header: {
      home: 'Accueil',
      dashboard: 'Tableau de bord',
      about: 'À propos',
      features: 'Fonctionnalités',
      donate: 'Soutenir',
      login: 'Se connecter',
      settings: 'Paramètres',
      changePassword: 'Changer de mot de passe',
      logout: 'Déconnexion',
    },
    home: {
      badge: 'PushIT pour les équipes produit',
      title: 'Gérez facilement vos notifications Push.',
      description:
        'Centralisez vos campagnes push dans un espace moderne, plus calme à parcourir et plus simple à prendre en main.',
      primary: 'Voir les fonctionnalités',
      secondary: 'Se connecter',
      register: {
        title: 'Créer un compte',
        subtitle: "Inscrivez-vous directement depuis l'accueil.",
      },
    },
    features: {
      badge: 'Fonctionnalités',
      title: 'Tout ce que le frontend couvre déjà.',
      description:
        'La page regroupe les workflows exposés par le backend ainsi que la configuration de la cible API.',
      sections: [
        {
          title: 'Fonctionnalités générales',
          items: [
            "Inscription, connexion, déconnexion et rafraîchissement du token JWT.",
            'Récupération du profil courant et mise à jour de la langue utilisateur.',
            'Langues supportées : FR, NL et EN.',
            'Gestion de session sécurisée par JWT côté frontend classique.',
          ],
        },
        {
          title: 'Fonctionnalités des applications',
          items: [
            "Liste, création, détail, modification et suppression d'une application.",
            "Activation, désactivation, révocation et régénération du token applicatif.",
            "Récupération des informations utiles pour l'intégration mobile ou API.",
            "Gestion complète du cycle de vie d'une application de push.",
          ],
        },
        {
          title: 'Fonctionnalités des devices',
          items: [
            'Liste, détail, modification et suppression des devices visibles.',
            "Visualisation des applications liées à un device.",
            'Liaison automatique via X-App-Token.',
            "Support du flux mobile : installation, scan QR code, récupération du push token et création ou mise à jour du lien côté backend.",
          ],
        },
        {
          title: 'Fonctionnalités des notifications',
          items: [
            "Création de notifications ciblées par application et liste explicite de devices.",
            'Liste, détail, envoi manuel et statistiques des notifications.',
            'Gestion des notifications futures : liste, détail, modification et suppression.',
            "Filtres par application, statut et date effective d'envoi, avec prise en compte des envois partiels et de `effective_scheduled_for`.",
          ],
        },
        {
          title: 'Fonctionnalités des périodes blanches',
          items: [
            'Gestion des périodes blanches par application ou par device.',
            'Support des périodes ONCE et RECURRING, avec modification, suppression et activation.',
            'Gestion des fenêtres qui passent minuit et des fenêtres contiguës.',
            "Impact métier distinct : décalage global de notification côté application, ou report de delivery côté device.",
          ],
        },
        {
          title: 'Fonctionnalité envoi par mail',
          items: [
            "Réception d'un email entrant et résolution de l'application via le préfixe destinataire.",
            "Transformation du sujet en titre et du contenu texte en message, avec planification via un marqueur `SEND_AT`.",
            "Contrôles d'accès sur domaine, expéditeur et appartenance de l'application ciblée.",
            "Gestion de l'idempotence via `message_id`, avec rejet des rejeux au contenu différent.",
          ],
        },
      ],
      backendTitle: 'Configuration backend',
      backendDescription:
        "Définissez ici l'URL de base de l'API utilisée par tout le frontend Angular.",
      submit: 'Enregistrer',
      saved: 'Enregistré',
    },
    donate: {
      badge: 'Soutenir',
      title: 'Soutenir une console plus simple.',
      description:
        "Si le projet vous aide, cette page sert de point d'ancrage pour un futur vrai flux de donation.",
      cards: [
        'Soutien ponctuel pour le maintien du projet',
        'Participation aux évolutions UX et i18n',
        'Aide au financement des itérations produit',
      ],
      button: 'Bientôt disponible',
    },
    about: {
      badge: 'À propos',
      title: 'À propos de PushIT.',
      description: 'PushIT est une console simple pour gérer vos notifications push.',
      sections: [
        {
          icon: 'pi-bolt',
          title: 'Le produit',
          body: 'PushIT centralise la gestion de vos applications, de vos devices et de vos campagnes de notifications push dans une console claire et moderne.',
        },
        {
          icon: 'pi-building',
          title: "L'éditeur",
          body: 'PushIT est conçu et maintenu par Foxugly, qui développe une petite famille d\'outils web soignés.',
        },
        {
          icon: 'pi-code',
          title: 'Technologie',
          body: 'Un backend Django REST, un frontend Angular et l\'envoi des notifications via Firebase Cloud Messaging.',
        },
      ],
    },
    auth: {
      eyebrow: 'Connexion',
      title: 'Accéder à votre espace.',
      description: 'Connectez-vous pour accéder au dashboard PushIT et gérer vos campagnes.',
      email: 'Email',
      password: 'Mot de passe',
      passwordPlaceholder: 'Mot de passe',
      rememberMe: 'Se souvenir de moi',
      forgotPassword: 'Mot de passe oublié ?',
      register: 'Inscription',
      submit: 'Se connecter',
      pending: 'Connexion...',
    },
    registerPage: {
      eyebrow: 'Inscription',
      title: 'Créer un compte PushIT.',
      description:
        'Inscrivez-vous pour accéder à la console et commencer à gérer vos applications et vos notifications.',
    },
    registerPanel: {
      defaultTitle: 'Inscription',
      defaultSubtitle: 'Compte utilisateur',
      email: 'Email',
      password: 'Mot de passe',
      passwordPlaceholder: 'Minimum 8 caractères',
      language: 'Langue',
      languagePlaceholder: 'Choisir une langue',
      submit: 'Créer le compte',
      pending: 'Création...',
      loginPrompt: 'Déjà un compte ?',
      loginLink: 'Se connecter',
      captchaRequired: 'Merci de valider le captcha anti-robot.',
      captchaFailed: 'Échec de la vérification anti-robot. Réessayez.',
      validation: {
        emailRequired: "L'email est requis.",
        emailInvalid: 'Saisissez une adresse email valide.',
        passwordRequired: 'Le mot de passe est requis.',
        passwordTooShort: 'Le mot de passe doit faire au moins 8 caractères.',
        languageRequired: 'La langue est requise.',
      },
    },
    forgotPassword: {
      eyebrow: 'Mot de passe oublié',
      title: "Récupérer l'accès.",
      description:
        'Saisissez votre email. Si un compte existe, nous vous enverrons un lien pour réinitialiser votre mot de passe.',
      email: 'Email',
      submit: 'Continuer',
      submitted:
        'Si un compte existe avec cet email, un lien de réinitialisation vient de vous être envoyé. Pensez à vérifier vos spams.',
      registerPrompt: "Besoin d'un compte ?",
      registerLink: 'Inscription',
      captchaRequired: 'Merci de valider le captcha anti-robot.',
      captchaFailed: 'Échec de la vérification anti-robot. Réessayez.',
    },
    resetPassword: {
      eyebrow: 'Réinitialisation',
      title: 'Choisir un nouveau mot de passe.',
      description: 'Saisissez votre nouveau mot de passe ci-dessous.',
      password: 'Nouveau mot de passe',
      passwordPlaceholder: 'Minimum 8 caractères',
      confirmPassword: 'Confirmer le mot de passe',
      passwordTooShort: 'Le mot de passe doit faire au moins 8 caractères.',
      passwordMismatch: 'Les mots de passe ne correspondent pas.',
      submit: 'Réinitialiser le mot de passe',
      success: 'Votre mot de passe a été réinitialisé. Vous pouvez maintenant vous connecter.',
      goToLogin: 'Se connecter',
      backToLogin: 'Retour à la connexion',
    },
    checkEmail: {
      title: 'Vérifiez votre boîte mail',
      intro: 'Nous avons envoyé un lien de confirmation à ',
      hint: 'Cliquez sur le lien pour activer votre compte, puis connectez-vous.',
      resend: 'Renvoyer le lien',
      resent: 'Si une confirmation est nécessaire, un nouveau lien a été envoyé.',
      backToLogin: 'Retour à la connexion',
    },
    confirmEmail: {
      title: 'Confirmation de l\'email',
      confirming: 'Confirmation en cours…',
      invalid: 'Ce lien de confirmation est invalide ou a expiré.',
      resendHint: 'Saisissez votre email pour recevoir un nouveau lien.',
      emailLabel: 'Email',
      resend: 'Renvoyer le lien',
      resent: 'Si une confirmation est nécessaire, un nouveau lien a été envoyé.',
      resendError: "Impossible d'envoyer le lien pour le moment. Réessayez plus tard.",
      backToLogin: 'Retour à la connexion',
    },
    footer: {
      rightsReserved: 'Tous droits réservés.',
      privacy: 'Politique de confidentialité',
    },
    console: {
      navigation: {
        eyebrow: 'Navigation',
        title: 'Menu console',
        tokenEyebrow: 'Token généré',
        copyButton: 'Copier',
        dismissButton: 'Masquer',
        tokenNote: "Le token brut n'est visible qu'une fois. Stockage côté serveur uniquement.",
        admin: {
          label: 'Administration',
          description: "Superviser l'état du backend et accéder à l'admin Django.",
        },
      },
      sections: [
        {
          label: 'Applications',
          description: 'Créer, modifier et gérer vos tokens.',
          icon: 'pi pi-briefcase',
          link: '/dashboard/applications',
          countKey: 'apps',
        },
        {
          label: 'Devices',
          description: 'Consulter et mettre à jour les terminaux liés.',
          icon: 'pi pi-mobile',
          link: '/dashboard/devices',
          countKey: 'devices',
        },
        {
          label: 'Notifications',
          description: 'Cibler, planifier et suivre les envois.',
          icon: 'pi pi-envelope',
          link: '/dashboard/notifications',
          countKey: 'notifications',
        },
        {
          label: 'Périodes blanches',
          description: 'Piloter les fenêtres de silence applicatives et device.',
          icon: 'pi pi-moon',
          link: '/dashboard/quiet-periods',
          countKey: 'quietPeriods',
        },
      ],
      dashboard: {
        eyebrow: 'Tableau de bord',
        title: "Vue d'ensemble",
        description: "Retrouvez l'état global de votre console et accédez rapidement aux écrans de gestion.",
        cta: 'Applications',
        metrics: {
          apps: 'Applications',
          activeApps: 'Actives',
          devices: 'Devices',
          notifications: 'Notifications',
          quietPeriods: 'Périodes blanches',
        },
      },
      settings: {
        eyebrow: 'Paramètres',
        title: 'Paramètres de la console',
        description: 'Cette page centralise la configuration frontend utilisée pour joindre le backend.',
        backendEyebrow: 'Backend',
        backendTitle: "Préfixe de l'API",
        apiUrl: 'URL API',
        language: 'Langue du compte',
        submit: 'Enregistrer',
        saved: 'Préférences enregistrées.',
        sessionEyebrow: 'Session',
        sessionTitle: 'Compte connecté',
        fallbackUser: 'Utilisateur',
        fallbackEmail: 'Email indisponible',
        activePrefix: 'Préfixe actif',
        activeLanguage: 'Langue active',
      },
      changePassword: {
        eyebrow: 'Mot de passe',
        title: 'Changer de mot de passe',
        description: "Le frontend est prêt à recevoir cette action, mais le backend Swagger fourni n'expose pas encore d'endpoint dédié.",
        backendEyebrow: 'État backend',
        backendTitle: 'Action non disponible',
        note:
          "Le Swagger expose actuellement `login`, `logout`, `me`, `refresh` et `register`, mais pas de route `change-password`. Quand l'endpoint sera disponible, cette page pourra accueillir le formulaire de mise à jour.",
      },
      applicationForm: {
        name: 'Nom',
        description: 'Description',
        namePlaceholder: 'Push mobile Europe',
        descriptionPlaceholder: 'Canal, environnement, usage...',
      },
      deviceForm: {
        name: 'Nom',
        platform: 'Plateforme',
        pushTokenStatus: 'Statut du push token',
      },
    },
  },
  nl: {
    header: {
      home: 'Home',
      dashboard: 'Dashboard',
      about: 'Over',
      features: 'Functies',
      donate: 'Steunen',
      login: 'Inloggen',
      settings: 'Instellingen',
      changePassword: 'Wachtwoord wijzigen',
      logout: 'Uitloggen',
    },
    home: {
      badge: 'PushIT voor productteams',
      title: 'Beheer je pushmeldingen eenvoudig.',
      description:
        'Centraliseer pushcampagnes in een moderne ruimte die rustiger leest en eenvoudiger in gebruik is.',
      primary: 'Bekijk de features',
      secondary: 'Inloggen',
      register: {
        title: 'Account aanmaken',
        subtitle: 'Registreer je rechtstreeks vanaf de homepagina.',
      },
    },
    features: {
      badge: 'Features',
      title: 'Alles wat de frontend al ondersteunt.',
      description:
        'Deze pagina groepeert de backend-workflows en de configuratie van de API-doelomgeving.',
      sections: [
        {
          title: 'Algemene functionaliteiten',
          items: [
            'Registratie, login, logout en refresh van het JWT-token.',
            'Ophalen van het huidige profiel en bijwerken van de gebruikerstaal.',
            'Ondersteunde talen: FR, NL en EN.',
            'Veilige sessiebeheer met JWT aan frontendzijde.',
          ],
        },
        {
          title: 'Applicatiefunctionaliteiten',
          items: [
            'Lijst, creatie, detail, wijziging en verwijdering van een applicatie.',
            'Activeren, deactiveren, intrekken en vernieuwen van het applicatietoken.',
            'Ophalen van de integratiegegevens voor mobile of API.',
            'Volledig beheer van de levenscyclus van een pushapplicatie.',
          ],
        },
        {
          title: 'Devicefunctionaliteiten',
          items: [
            'Lijst, detail, wijziging en verwijdering van zichtbare devices.',
            'Visualisatie van de applicaties die aan een device gekoppeld zijn.',
            'Automatische koppeling via X-App-Token.',
            'Ondersteuning van de mobiele flow: installatie, QR-scan, ophalen van de push token en aanmaak of update van de koppeling in de backend.',
          ],
        },
        {
          title: 'Notificatiefuncties',
          items: [
            'Aanmaken van gerichte notificaties per applicatie en expliciete device-lijst.',
            'Lijst, detail, manuele verzending en statistieken van notificaties.',
            'Beheer van toekomstige notificaties: lijst, detail, wijziging en verwijdering.',
            'Filters op applicatie, status en effectieve verzenddatum, inclusief partiele verzendingen en `effective_scheduled_for`.',
          ],
        },
        {
          title: 'Stille-periodefunctionaliteiten',
          items: [
            'Beheer van stille periodes per applicatie of per device.',
            'Ondersteuning voor ONCE- en RECURRING-periodes, met wijziging, verwijdering en activatie.',
            'Beheer van vensters die over middernacht lopen en aaneengesloten vensters.',
            'Duidelijke business-impact: globale verschuiving op applicatieniveau, of uitgestelde delivery op deviceniveau.',
          ],
        },
        {
          title: 'Mailverzendfunctionaliteit',
          items: [
            'Ontvangst van inkomende mail en koppeling aan de applicatie via het bestemmingsprefix.',
            'Omzetting van onderwerp naar titel en platte tekst naar bericht, met planning via `SEND_AT`.',
            'Toegangscontroles op domein, afzender en eigendom van de doelapplicatie.',
            'Idempotentie via `message_id`, met weigering bij hergebruik met andere inhoud.',
          ],
        },
      ],
      backendTitle: 'Backendconfiguratie',
      backendDescription:
        'Definieer hier de basis-URL van de API die door de Angular-frontend wordt gebruikt.',
      submit: 'Opslaan',
      saved: 'Opgeslagen',
    },
    donate: {
      badge: 'Donate',
      title: 'Steun een eenvoudigere console.',
      description:
        'Als het project nuttig is, dient deze pagina als basis voor een toekomstige donatiestroom.',
      cards: [
        'Eenmalige steun voor onderhoud van het project',
        'Bijdrage aan UX- en i18n-verbeteringen',
        'Ondersteuning voor productiteraties',
      ],
      button: 'Binnenkort beschikbaar',
    },
    about: {
      badge: 'Over',
      title: 'Over PushIT.',
      description: 'PushIT is een eenvoudige console om je pushmeldingen te beheren.',
      sections: [
        {
          icon: 'pi-bolt',
          title: 'Het product',
          body: 'PushIT centraliseert het beheer van je applicaties, devices en pushcampagnes in een heldere, moderne console.',
        },
        {
          icon: 'pi-building',
          title: 'De uitgever',
          body: 'PushIT wordt ontworpen en onderhouden door Foxugly, dat een kleine familie van verzorgde webtools bouwt.',
        },
        {
          icon: 'pi-code',
          title: 'Technologie',
          body: 'Een Django REST-backend, een Angular-frontend en notificaties via Firebase Cloud Messaging.',
        },
      ],
    },
    auth: {
      eyebrow: 'Inloggen',
      title: 'Toegang tot je ruimte.',
      description: 'Log in om het PushIT-dashboard te openen en je campagnes te beheren.',
      email: 'Email',
      password: 'Wachtwoord',
      passwordPlaceholder: 'Wachtwoord',
      rememberMe: 'Onthoud mij',
      forgotPassword: 'Wachtwoord vergeten?',
      register: 'Registreren',
      submit: 'Inloggen',
      pending: 'Bezig met inloggen...',
    },
    registerPage: {
      eyebrow: 'Registratie',
      title: 'Maak een PushIT-account aan.',
      description:
        'Registreer je om toegang te krijgen tot de console en je applicaties en notificaties te beheren.',
    },
    registerPanel: {
      defaultTitle: 'Registratie',
      defaultSubtitle: 'Gebruikersaccount',
      email: 'Email',
      password: 'Wachtwoord',
      passwordPlaceholder: 'Minimaal 8 tekens',
      language: 'Taal',
      languagePlaceholder: 'Kies een taal',
      submit: 'Account aanmaken',
      pending: 'Bezig met aanmaken...',
      loginPrompt: 'Al een account?',
      loginLink: 'Inloggen',
      captchaRequired: 'Bevestig de anti-robotcaptcha.',
      captchaFailed: 'Anti-robotverificatie mislukt. Probeer opnieuw.',
      validation: {
        emailRequired: 'E-mail is verplicht.',
        emailInvalid: 'Voer een geldig e-mailadres in.',
        passwordRequired: 'Wachtwoord is verplicht.',
        passwordTooShort: 'Het wachtwoord moet minstens 8 tekens bevatten.',
        languageRequired: 'Taal is verplicht.',
      },
    },
    forgotPassword: {
      eyebrow: 'Wachtwoord vergeten',
      title: 'Toegang herstellen.',
      description:
        'Voer je email in. Als er een account bestaat, sturen we je een link om je wachtwoord opnieuw in te stellen.',
      email: 'Email',
      submit: 'Doorgaan',
      submitted:
        'Als er een account met dit email bestaat, is er zojuist een reset-link verstuurd. Controleer ook je spam-map.',
      registerPrompt: 'Nog geen account?',
      registerLink: 'Registreren',
      captchaRequired: 'Bevestig de anti-robotcaptcha.',
      captchaFailed: 'Anti-robotverificatie mislukt. Probeer opnieuw.',
    },
    resetPassword: {
      eyebrow: 'Opnieuw instellen',
      title: 'Kies een nieuw wachtwoord.',
      description: 'Voer hieronder je nieuwe wachtwoord in.',
      password: 'Nieuw wachtwoord',
      passwordPlaceholder: 'Minimaal 8 tekens',
      confirmPassword: 'Bevestig wachtwoord',
      passwordTooShort: 'Het wachtwoord moet minstens 8 tekens bevatten.',
      passwordMismatch: 'De wachtwoorden komen niet overeen.',
      submit: 'Wachtwoord opnieuw instellen',
      success: 'Je wachtwoord is opnieuw ingesteld. Je kunt nu inloggen.',
      goToLogin: 'Inloggen',
      backToLogin: 'Terug naar inloggen',
    },
    checkEmail: {
      title: 'Controleer je e-mail',
      intro: 'We hebben een bevestigingslink gestuurd naar ',
      hint: 'Klik op de link om je account te activeren en log daarna in.',
      resend: 'Link opnieuw versturen',
      resent: 'Indien een bevestiging nodig is, is een nieuwe link verstuurd.',
      backToLogin: 'Terug naar inloggen',
    },
    confirmEmail: {
      title: 'E-mail bevestigen',
      confirming: 'Bezig met bevestigen…',
      invalid: 'Deze bevestigingslink is ongeldig of verlopen.',
      resendHint: 'Voer je e-mail in om een nieuwe link te ontvangen.',
      emailLabel: 'E-mail',
      resend: 'Link opnieuw versturen',
      resent: 'Indien een bevestiging nodig is, is een nieuwe link verstuurd.',
      resendError: 'De link kan nu niet worden verzonden. Probeer het later opnieuw.',
      backToLogin: 'Terug naar inloggen',
    },
    footer: {
      rightsReserved: 'Alle rechten voorbehouden.',
      privacy: 'Privacybeleid',
    },
    console: {
      navigation: {
        eyebrow: 'Navigatie',
        title: 'Consolemenu',
        tokenEyebrow: 'Token gegenereerd',
        copyButton: 'Kopieren',
        dismissButton: 'Verbergen',
        tokenNote: 'Het ruwe token is slechts eenmaal zichtbaar. Opslag alleen aan serverzijde.',
        admin: {
          label: 'Beheer',
          description: 'De status van de backend bewaken en de Django-admin openen.',
        },
      },
      sections: [
        {
          label: 'Applicaties',
          description: 'Aanmaken, bewerken en tokens beheren.',
          icon: 'pi pi-briefcase',
          link: '/dashboard/applications',
          countKey: 'apps',
        },
        {
          label: 'Devices',
          description: 'Gekoppelde toestellen raadplegen en bijwerken.',
          icon: 'pi pi-mobile',
          link: '/dashboard/devices',
          countKey: 'devices',
        },
        {
          label: 'Notificaties',
          description: 'Verzendingen targeten, plannen en opvolgen.',
          icon: 'pi pi-envelope',
          link: '/dashboard/notifications',
          countKey: 'notifications',
        },
        {
          label: 'Stille periodes',
          description: 'Applicatieve en device-stiltevensters beheren.',
          icon: 'pi pi-moon',
          link: '/dashboard/quiet-periods',
          countKey: 'quietPeriods',
        },
      ],
      dashboard: {
        eyebrow: 'Dashboard',
        title: 'Overzicht',
        description: 'Bekijk de globale staat van je console en ga snel naar de beheerschermen.',
        cta: 'Applicaties',
        metrics: {
          apps: 'Applicaties',
          activeApps: 'Actief',
          devices: 'Devices',
          notifications: 'Notificaties',
          quietPeriods: 'Stille periodes',
        },
      },
      settings: {
        eyebrow: 'Instellingen',
        title: 'Console-instellingen',
        description: 'Deze pagina centraliseert de frontendconfiguratie om de backend te bereiken.',
        backendEyebrow: 'Backend',
        backendTitle: 'API-prefix',
        apiUrl: 'API-URL',
        language: 'Accounttaal',
        submit: 'Opslaan',
        saved: 'Voorkeuren opgeslagen.',
        sessionEyebrow: 'Sessie',
        sessionTitle: 'Ingelogd account',
        fallbackUser: 'Gebruiker',
        fallbackEmail: 'Email niet beschikbaar',
        activePrefix: 'Actieve prefix',
        activeLanguage: 'Actieve taal',
      },
      changePassword: {
        eyebrow: 'Wachtwoord',
        title: 'Wachtwoord wijzigen',
        description: 'De frontend is klaar voor deze actie, maar de meegeleverde backend exposeert nog geen specifieke endpoint.',
        backendEyebrow: 'Backendstatus',
        backendTitle: 'Actie niet beschikbaar',
        note:
          'De Swagger exposeert momenteel `login`, `logout`, `me`, `refresh` en `register`, maar geen route `change-password`. Zodra die endpoint beschikbaar is, kan deze pagina het updateformulier bevatten.',
      },
      applicationForm: {
        name: 'Naam',
        description: 'Beschrijving',
        namePlaceholder: 'Push mobile Europe',
        descriptionPlaceholder: 'Kanaal, omgeving, gebruik...',
      },
      deviceForm: {
        name: 'Naam',
        platform: 'Platform',
        pushTokenStatus: 'Push-tokenstatus',
      },
    },
  },
  en: {
    header: {
      home: 'Home',
      dashboard: 'Dashboard',
      about: 'About',
      features: 'Features',
      donate: 'Support',
      login: 'Log in',
      settings: 'Settings',
      changePassword: 'Change password',
      logout: 'Log out',
    },
    home: {
      badge: 'PushIT for product teams',
      title: 'Manage your push notifications easily.',
      description:
        'Centralize push campaigns in a modern workspace designed to feel lighter and easier to operate.',
      primary: 'See features',
      secondary: 'Log in',
      register: {
        title: 'Create an account',
        subtitle: 'Sign up directly from the homepage.',
      },
    },
    features: {
      badge: 'Features',
      title: 'Everything the frontend already covers.',
      description:
        'This page gathers the backend workflows already exposed in the UI along with API target configuration.',
      sections: [
        {
          title: 'General capabilities',
          items: [
            'User sign-up, sign-in, sign-out and JWT refresh.',
            'Current profile retrieval and user language update.',
            'Supported languages: FR, NL and EN.',
            'Secure JWT-based session handling on the frontend.',
          ],
        },
        {
          title: 'Application capabilities',
          items: [
            'List, create, inspect, update and delete applications.',
            'Activate, deactivate, revoke and regenerate the application token.',
            'Expose the data needed for mobile or API integration.',
            'Cover the full push application lifecycle.',
          ],
        },
        {
          title: 'Device capabilities',
          items: [
            'List, inspect, update and delete visible devices.',
            'Show which applications a device is linked to.',
            'Automatically link a device through X-App-Token.',
            'Support the mobile flow: install, QR scan, retrieve push token and create or update the backend link.',
          ],
        },
        {
          title: 'Notification capabilities',
          items: [
            'Create targeted notifications by application and explicit device list.',
            'List, inspect, send manually and monitor notification statistics.',
            'Manage future notifications: list, inspect, update and delete.',
            'Filter by application, status and effective send date, including partial delivery handling and `effective_scheduled_for`.',
          ],
        },
        {
          title: 'Quiet period capabilities',
          items: [
            'Manage quiet periods at application or device level.',
            'Support ONCE and RECURRING periods, with update, delete and activation.',
            'Handle windows crossing midnight and contiguous windows.',
            'Reflect the distinct business impact: global notification shift for applications, device-only delivery delay for devices.',
          ],
        },
        {
          title: 'Email delivery capability',
          items: [
            'Receive inbound email and resolve the target application from the recipient prefix.',
            'Turn the subject into a notification title and the text body into a message, with optional `SEND_AT` scheduling.',
            'Validate domain, sender and target application ownership.',
            'Handle idempotency through `message_id`, rejecting replays with different content.',
          ],
        },
      ],
      backendTitle: 'Backend configuration',
      backendDescription:
        'Set here the API base URL used across the Angular frontend.',
      submit: 'Save',
      saved: 'Saved',
    },
    donate: {
      badge: 'Donate',
      title: 'Support a simpler console.',
      description:
        'If the project helps you, this page acts as a placeholder for a future real donation flow.',
      cards: [
        'One-off support for project maintenance',
        'Contribution to UX and i18n improvements',
        'Help fund product iterations',
      ],
      button: 'Coming soon',
    },
    about: {
      badge: 'About',
      title: 'About PushIT.',
      description: 'PushIT is a simple console to manage your push notifications.',
      sections: [
        {
          icon: 'pi-bolt',
          title: 'The product',
          body: 'PushIT centralizes the management of your applications, devices and push campaigns in a clear, modern console.',
        },
        {
          icon: 'pi-building',
          title: 'The publisher',
          body: 'PushIT is designed and maintained by Foxugly, which builds a small family of polished web tools.',
        },
        {
          icon: 'pi-code',
          title: 'Technology',
          body: 'A Django REST backend, an Angular frontend and notifications delivered through Firebase Cloud Messaging.',
        },
      ],
    },
    auth: {
      eyebrow: 'Log in',
      title: 'Access your workspace.',
      description: 'Log in to access the PushIT dashboard and manage your campaigns.',
      email: 'Email',
      password: 'Password',
      passwordPlaceholder: 'Password',
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot password?',
      register: 'Sign up',
      submit: 'Log in',
      pending: 'Logging in...',
    },
    registerPage: {
      eyebrow: 'Sign up',
      title: 'Create a PushIT account.',
      description:
        'Sign up to access the console and start managing your applications and notifications.',
    },
    registerPanel: {
      defaultTitle: 'Sign up',
      defaultSubtitle: 'User account',
      email: 'Email',
      password: 'Password',
      passwordPlaceholder: 'Minimum 8 characters',
      language: 'Language',
      languagePlaceholder: 'Choose a language',
      submit: 'Create account',
      pending: 'Creating...',
      loginPrompt: 'Already have an account?',
      loginLink: 'Log in',
      captchaRequired: 'Please complete the anti-bot captcha.',
      captchaFailed: 'Anti-bot verification failed. Please try again.',
      validation: {
        emailRequired: 'Email is required.',
        emailInvalid: 'Enter a valid email address.',
        passwordRequired: 'Password is required.',
        passwordTooShort: 'Password must be at least 8 characters.',
        languageRequired: 'Language is required.',
      },
    },
    forgotPassword: {
      eyebrow: 'Forgot password',
      title: 'Recover access.',
      description:
        'Enter your email. If an account exists, we will send you a link to reset your password.',
      email: 'Email',
      submit: 'Continue',
      submitted:
        'If an account exists for that email, a reset link has just been sent. Remember to check your spam folder.',
      registerPrompt: 'Need an account?',
      registerLink: 'Sign up',
      captchaRequired: 'Please complete the anti-bot captcha.',
      captchaFailed: 'Anti-bot verification failed. Please try again.',
    },
    resetPassword: {
      eyebrow: 'Reset password',
      title: 'Choose a new password.',
      description: 'Enter your new password below.',
      password: 'New password',
      passwordPlaceholder: 'Minimum 8 characters',
      confirmPassword: 'Confirm password',
      passwordTooShort: 'Password must be at least 8 characters.',
      passwordMismatch: 'Passwords do not match.',
      submit: 'Reset password',
      success: 'Your password has been reset. You can now sign in.',
      goToLogin: 'Sign in',
      backToLogin: 'Back to sign in',
    },
    checkEmail: {
      title: 'Check your email',
      intro: 'We sent a confirmation link to ',
      hint: 'Click the link to activate your account, then sign in.',
      resend: 'Resend the link',
      resent: 'If a confirmation is needed, a new link has been sent.',
      backToLogin: 'Back to sign in',
    },
    confirmEmail: {
      title: 'Email confirmation',
      confirming: 'Confirming…',
      invalid: 'This confirmation link is invalid or has expired.',
      resendHint: 'Enter your email to get a new link.',
      emailLabel: 'Email',
      resend: 'Resend the link',
      resent: 'If a confirmation is needed, a new link has been sent.',
      resendError: 'Could not send the link right now. Please try again later.',
      backToLogin: 'Back to sign in',
    },
    footer: {
      rightsReserved: 'All rights reserved.',
      privacy: 'Privacy policy',
    },
    console: {
      navigation: {
        eyebrow: 'Navigation',
        title: 'Console menu',
        tokenEyebrow: 'Token generated',
        copyButton: 'Copy',
        dismissButton: 'Hide',
        tokenNote: 'The raw token is only visible once. Server-side storage only.',
        admin: {
          label: 'Administration',
          description: 'Monitor backend health and open the Django admin.',
        },
      },
      sections: [
        {
          label: 'Applications',
          description: 'Create, edit and manage your tokens.',
          icon: 'pi pi-briefcase',
          link: '/dashboard/applications',
          countKey: 'apps',
        },
        {
          label: 'Devices',
          description: 'Inspect and update linked devices.',
          icon: 'pi pi-mobile',
          link: '/dashboard/devices',
          countKey: 'devices',
        },
        {
          label: 'Notifications',
          description: 'Target, schedule and track deliveries.',
          icon: 'pi pi-envelope',
          link: '/dashboard/notifications',
          countKey: 'notifications',
        },
        {
          label: 'Quiet periods',
          description: 'Control application and device quiet windows.',
          icon: 'pi pi-moon',
          link: '/dashboard/quiet-periods',
          countKey: 'quietPeriods',
        },
      ],
      dashboard: {
        eyebrow: 'Dashboard',
        title: 'Overview',
        description: 'See the global state of your console and jump quickly to management screens.',
        cta: 'Applications',
        metrics: {
          apps: 'Applications',
          activeApps: 'Active',
          devices: 'Devices',
          notifications: 'Notifications',
          quietPeriods: 'Quiet periods',
        },
      },
      settings: {
        eyebrow: 'Settings',
        title: 'Console settings',
        description: 'This page centralizes the frontend configuration used to reach the backend.',
        backendEyebrow: 'Backend',
        backendTitle: 'API prefix',
        apiUrl: 'API URL',
        language: 'Account language',
        submit: 'Save',
        saved: 'Preferences saved.',
        sessionEyebrow: 'Session',
        sessionTitle: 'Signed-in account',
        fallbackUser: 'User',
        fallbackEmail: 'Email unavailable',
        activePrefix: 'Active prefix',
        activeLanguage: 'Active language',
      },
      changePassword: {
        eyebrow: 'Password',
        title: 'Change password',
        description: 'The frontend is ready for this action, but the provided backend does not expose a dedicated endpoint yet.',
        backendEyebrow: 'Backend status',
        backendTitle: 'Action unavailable',
        note:
          'The Swagger currently exposes `login`, `logout`, `me`, `refresh` and `register`, but no `change-password` route. When the endpoint becomes available, this page can host the update form.',
      },
      applicationForm: {
        name: 'Name',
        description: 'Description',
        namePlaceholder: 'Push mobile Europe',
        descriptionPlaceholder: 'Channel, environment, usage...',
      },
      deviceForm: {
        name: 'Name',
        platform: 'Platform',
        pushTokenStatus: 'Push token status',
      },
    },
  },
} as const;

@Injectable({ providedIn: 'root' })
export class AppCopyService {
  private readonly i18n = inject(PublicI18nService);

  readonly current = computed(() => APP_COPY[this.i18n.language()]);
}
