import { computed, inject, Injectable } from '@angular/core';

import { LanguageCode, PublicI18nService } from './public-i18n.service';

export const CONSOLE_COPY = {
  fr: {
    applications: {
      title: 'Gestion des applications',
      total: 'Total',
      active: 'Actives',
      refresh: 'Rafraîchir',
      add: 'Ajouter',
      empty: 'Aucune application pour ce compte.',
      loading: "Chargement de l'application...",
      noDescription: 'Aucune description.',
      statuses: { active: 'active', inactive: 'inactive' },
      table: { name: 'Nom', description: 'Description', prefix: 'Préfixe', status: 'Statut', createdAt: 'Créée le', actions: 'Actions' },
      actions: { view: 'Voir le détail', edit: 'Éditer', activate: 'Activer', deactivate: 'Désactiver', regenerate: 'Régénérer le token', revoke: 'Révoquer le token', delete: 'Supprimer', qrCode: 'QR code' },
      qr: { title: 'QR code du token', scanHint: "Scannez ce QR code avec l'app mobile PushIT pour lier un appareil.", tokenOnce: "Le token n'est visible qu'une fois. Régénérez-le pour afficher son QR code (les appareils déjà liés ne sont pas affectés).", regenerate: 'Régénérer et afficher', error: 'Impossible de générer le QR code.', loading: 'Génération du QR code…', copyToken: 'Copier le token', copied: 'Token copié dans le presse-papier.', copyFailed: 'Impossible de copier le token.', downloadQr: 'Télécharger le QR code', downloadToken: 'Télécharger le token', saveNotice: "⚠️ Ce token n'est affiché qu'une seule fois : copiez-le ou téléchargez-le maintenant et conservez-le en lieu sûr." },
      logo: { label: 'Logo', none: 'Aucun logo', remove: 'Supprimer le logo', choose: 'Choisir une image', hint: 'Glissez-déposez une image ici (PNG/JPG, max 2 Mo).', cropHint: 'Déplacez et zoomez pour cadrer dans le cercle.', zoomIn: 'Zoomer', zoomOut: 'Dézoomer', apply: 'Appliquer', change: "Changer d'image" },
      dialog: { createTitle: 'Créer une application', editTitle: 'Modifier une application', create: "Créer l'application", creating: 'Création...', save: 'Enregistrer', saving: 'Enregistrement...' },
      alerts: { created: 'Application créée. Ouvrez le QR code pour voir, copier ou télécharger le token.', updated: 'Application {name} mise à jour.', activated: 'Application activée avec succès.', deactivated: 'Application désactivée avec succès.', regenerated: 'Nouveau token généré. Ouvrez le QR code pour le voir, le copier ou le télécharger.', revoked: 'Le token de cette application a été révoqué.', deleted: 'Application {name} supprimée.' },
      errors: { create: "Impossible de créer l'application.", toggle: "Impossible de mettre à jour l'état de l'application.", regenerate: 'Impossible de régénérer le token.', revoke: 'Impossible de révoquer le token.', invalidId: 'Identifiant application invalide.' },
      confirmDelete: 'Supprimer l\'application "{name}" ?',
    },
    devices: {
      title: 'Inventaire et liaison des devices',
      countLabel: 'devices',
      refresh: 'Rafraîchir',
      add: 'Ajouter',
      empty: 'Aucun device lié pour ce compte.',
      loading: 'Chargement des devices...',
      none: 'aucune',
      never: 'Jamais',
      table: { name: 'Nom', platform: 'Plateforme', token: 'Token', applications: 'Applications', lastActivity: 'Dernière activité', actions: 'Actions', prefix: 'Préfixe', status: 'Statut', createdAt: 'Créée le' },
      actions: { view: 'Voir le détail', edit: 'Éditer', delete: 'Supprimer', useLatestToken: 'Utiliser le dernier token généré', link: 'Lier le device', linking: 'Association...', save: 'Enregistrer', saving: 'Enregistrement...' },
      dialog: { createTitle: 'Lier un device', editTitle: 'Modifier le device' },
      createForm: { appToken: 'X-App-Token', appTokenPlaceholder: 'Coller le token brut ici', deviceName: 'Nom du device', deviceNamePlaceholder: 'iPhone Marie', platform: 'Plateforme', pushToken: 'Push token', pushTokenPlaceholder: 'ExponentPushToken...' },
      alerts: { updated: 'Device mis à jour avec succès.', deleted: 'Device supprimé.', linked: 'Device {deviceId} lié à l\'application {applicationId}.' },
      errors: { missingAppToken: 'Renseignez un X-App-Token pour lier un device.', invalidId: 'Identifiant device invalide.', loading: 'Chargement du device...' },
      confirmDelete: 'Supprimer le device "{name}" ?',
    },
    notifications: {
      title: 'Notifications utilisateur',
      history: 'Historique',
      future: 'Futures',
      shifted: 'Décalées',
      refresh: 'Rafraîchir',
      add: 'Ajouter',
      empty: 'Aucune notification pour ces filtres.',
      loading: 'Chargement des notifications...',
      immediate: 'immédiat',
      scheduledSubtext: 'Planifiée',
      filters: { application: 'Application', device: 'Device', status: 'Statut', from: 'Effectif à partir de', to: "Effectif jusqu'à", allApps: 'Toutes', allDevices: 'Tous', allStatuses: 'Tous', apply: 'Appliquer', reset: 'Réinitialiser' },
      table: { name: 'Nom', application: 'Application', message: 'Message', status: 'Statut', effective: 'Effective', actions: 'Actions' },
      actions: { view: 'Voir le détail', send: 'Envoyer', resend: 'Renvoyer', edit: 'Éditer', delete: 'Supprimer' },
      dialog: { createTitle: 'Créer une notification', editTitle: 'Modifier une notification future', create: 'Créer la notification', creating: 'Création...', save: 'Enregistrer', saving: 'Sauvegarde...' },
      form: { application: 'Application', applicationPlaceholder: 'Choisir...', devices: 'Devices ciblés', devicesPlaceholder: 'Choisir un ou plusieurs devices', devicesHelp: "Seuls les devices actifs liés à l'application sélectionnée sont proposés.", title: 'Titre', titlePlaceholder: 'Promo weekend', message: 'Message', messagePlaceholder: 'Votre message push', schedule: 'Planification optionnelle', newDate: 'Nouvelle date' },
      alerts: { createdImmediate: 'Notification immédiate créée.', sentImmediate: 'Notification envoyée.', createdScheduled: 'Notification planifiée créée.', updated: 'Notification future mise à jour.', deleted: 'Notification future "{title}" supprimée.', queued: 'Notification {notificationId} placée dans la file {taskId}.' },
      confirmDelete: 'Supprimer la notification future "{title}" ?',
      statusLabels: { draft: 'brouillon', scheduled: 'planifiée', queued: 'en file', processing: 'en cours', sent: 'envoyée', partial: 'partielle', failed: 'échouée', no_target: 'sans cible', shifted: 'décalée' },
      typeLabels: { future: 'Future', history: 'Historique' },
      errors: { invalidId: 'Identifiant notification invalide.', loading: 'Chargement de la notification...' },
      validation: { title: 'Champs manquants', detail: 'Veuillez remplir tous les champs obligatoires (application, appareils, titre et message).' },
    },
    quietPeriods: {
      title: 'Gestion des fenêtres de silence',
      refresh: 'Rafraîchir',
      add: 'Ajouter',
      empty: 'Aucune période blanche configurée.',
      loading: 'Chargement des périodes blanches...',
      targetNone: 'Aucune cible',
      targetUnknownApplication: 'Application inconnue',
      targetUnknownDevice: 'Device inconnu',
      missingTargets: 'Aucune application ou aucun device disponible pour créer une période blanche.',
      missingParent: 'Sélectionnez une cible valide avant de créer une période blanche.',
      table: { target: 'Cible', name: 'Nom', type: 'Type', rule: 'Règle', status: 'Statut', actions: 'Actions' },
      dialog: { createTitle: 'Nouvelle période blanche', editTitle: 'Modifier une période blanche', create: 'Créer la période', update: 'Mettre à jour', saving: 'Enregistrement...' },
      scopeLabels: { application: 'Application', device: 'Device' },
      typeLabels: { once: 'Ponctuelle', recurring: 'Récurrente', badgeOnce: 'once', badgeRecurring: 'recurring' },
      statusLabels: { active: 'active', inactive: 'inactive' },
      form: { target: 'Cible', device: 'Device', application: 'Application', selectPlaceholder: 'Choisir...', name: 'Nom', namePlaceholder: 'Nuit marketing', type: 'Type', recurrenceDays: 'Jours de récurrence', startTime: 'Heure de début', endTime: 'Heure de fin', startAt: 'Début', endAt: 'Fin', active: 'Période active' },
      weekdays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim'],
      defaultNames: { application: 'Silence application', device: 'Silence device' },
      alerts: { created: 'Période blanche créée.', updated: 'Période blanche mise à jour.', deleted: 'Période blanche "{name}" supprimée.' },
      actions: { edit: 'Éditer', delete: 'Supprimer' },
      confirmDelete: 'Supprimer la période blanche "{name}" ?',
      validation: { onceRequired: 'Une période ponctuelle demande une date de début et une date de fin.', recurringRequired: 'Une période récurrente demande des jours et une plage horaire.', required: 'Ce champ est obligatoire.', selectOneDay: 'Sélectionnez au moins un jour.', endAfterStart: 'La fin de la période blanche doit être après le début.', differentEndTime: "L'heure de fin doit être différente de l'heure de début." },
    },
    applicationDetail: {
      back: 'Retour aux applications',
      eyebrow: 'Application',
      fallbackTitle: 'Détail application',
      retry: 'Réessayer',
      editTooltip: "Éditer l'application",
      loading: "Chargement de l'application...",
      descriptionTitle: 'Description',
      descriptionEmpty: 'Aucune description disponible pour cette application.',
      inboundEmailTitle: 'Adresse email de notification',
      inboundEmailLabel: 'Adresse email',
      inboundEmailCopy: "Copier l'adresse",
      inboundEmailCopied: 'Adresse email copiée.',
      inboundEmailCopyFailed: "Impossible de copier l'adresse email.",
      inboundEmailHelpTitle: 'Envoyer une notification par email',
      inboundEmailHelp: {
        intro: 'Envoyez un email à cette adresse pour créer une notification sur cette application.',
        subject: "Le sujet de l'email devient le titre de la notification.",
        body: "Le contenu texte de l'email devient le message.",
        schedule: 'Planification possible avec [SEND_AT:ISO_DATETIME] dans le sujet.',
        sender: "L'expéditeur doit être l'email du propriétaire de l'application.",
      },
      devicesTitle: 'Devices liés',
      devicesEmpty: 'Aucun device lié à cette application.',
      notificationsTitle: 'Notifications',
      notificationsEmpty: 'Aucune notification liée à cette application.',
      quietPeriodsTitle: 'Périodes blanches',
      quietPeriodsEmpty: 'Aucune période blanche liée à cette application.',
      statusTitle: 'Statut',
      table: { name: 'Nom', platform: 'Plateforme', pushStatus: 'Statut push', lastActivity: 'Dernière activité', prefix: 'Préfixe', status: 'Statut', createdAt: 'Créée le', title: 'Titre', type: 'Type', effective: 'Effective', actions: 'Actions' },
      facts: { id: 'ID', name: 'Nom', tokenPrefix: 'Préfixe token', status: 'Statut', lastUsed: 'Dernière utilisation', revokedToken: 'Token révoqué', createdAt: 'Créée le' },
      statusLabels: { active: 'Active', inactive: 'Inactive', never: 'Jamais', no: 'Non', immediate: 'Immédiat', once: 'once', recurring: 'recurring' },
      notificationTypes: { future: 'Future', history: 'Historique' },
      actions: { view: 'Voir le détail' },
      dialog: { title: "Modifier l'application", save: 'Enregistrer', saving: 'Enregistrement...' },
      logo: { label: 'Logo', none: 'Aucun logo', remove: 'Supprimer le logo', updated: 'Logo mis à jour.', removed: 'Logo supprimé.', choose: 'Choisir une image', hint: 'Glissez-déposez une image ici (PNG/JPG, max 2 Mo).', cropHint: 'Déplacez et zoomez pour cadrer dans le cercle.', zoomIn: 'Zoomer', zoomOut: 'Dézoomer', apply: 'Appliquer', change: "Changer d'image" },
      regenerateEmail: {
        label: "Adresse email d'ingestion",
        button: "Régénérer l'adresse",
        pending: 'Régénération...',
        hint: "Génère une nouvelle adresse aléatoire ; l'ancienne cessera de fonctionner.",
        confirm: "Régénérer l'adresse email de « {name} » ? L'adresse actuelle cessera immédiatement de fonctionner.",
        success: 'Nouvelle adresse email générée.',
        error: "Impossible de régénérer l'adresse email.",
      },
      aliasStatus: {
        title: 'Vérifier l\'alias email entrant',
        button: 'Vérifier l\'alias',
        pending: 'Vérification...',
        active: 'Alias actif',
        missing: 'Alias absent',
        missingHint: 'L\'alias n\'existe pas côté Exchange. Régénérez l\'adresse ou contactez l\'équipe ops.',
        unavailable: 'Vérification indisponible (Exchange non configuré)',
        unverifiable: 'Impossible de vérifier',
        error: 'Impossible de vérifier l\'alias.',
      },
      errors: { invalidId: 'Identifiant application invalide.', logo: 'Impossible de mettre à jour le logo.' },
    },
    deviceDetail: {
      back: 'Retour aux devices',
      eyebrow: 'Device',
      fallbackTitle: 'Détail device',
      editTooltip: 'Éditer le device',
      loading: 'Chargement du device...',
      applicationsTitle: 'Applications liées',
      applicationsEmpty: 'Aucune application liée.',
      unlinkedTitle: 'Applications déliées',
      unlinkedOn: 'délié le',
      unlinkedUnknownDate: 'date inconnue',
      unlinkSources: { deviceButton: "depuis l'appareil", inbox: "depuis l'inbox", takeover: 'réattribué à un autre compte', unknown: 'source inconnue' },
      statusTitle: 'Statut',
      table: { name: 'Nom', prefix: 'Préfixe', status: 'Statut', createdAt: 'Créée le', actions: 'Actions' },
      facts: { id: 'ID', name: 'Nom', platform: 'Plateforme', tokenStatus: 'Statut token', lastActivity: 'Dernière activité', createdAt: 'Créé le' },
      labels: { never: 'Jamais', active: 'active', inactive: 'inactive' },
      actions: { view: 'Voir le détail' },
      dialog: { title: 'Modifier le device', save: 'Enregistrer', saving: 'Enregistrement...' },
      errors: { invalidId: 'Identifiant device invalide.' },
      notifications: {
        title: 'Notifications reçues',
        allApps: 'Toutes les applications',
        filterLabel: 'Filtrer par application',
        empty: 'Aucune notification livrée à ce device.',
        unknown: 'inconnu',
        table: { title: 'Titre', application: 'Application', delivery: 'Livraison', sentAt: 'Envoyée le', actions: 'Actions' },
      },
    },
    notificationDetail: {
      back: 'Retour aux notifications',
      eyebrow: 'Notification',
      fallbackTitle: 'Détail notification',
      editTooltip: 'Éditer la notification',
      loading: 'Chargement de la notification...',
      messageTitle: 'Message',
      devicesTitle: 'Devices ciblés',
      devicesEmpty: 'Aucun device cible résolu pour cette notification.',
      statusTitle: 'Statut',
      note: "`effective_scheduled_for` tient compte uniquement des périodes blanches application. Les périodes device peuvent retarder une delivery sans changer cette date.",
      table: { name: 'Nom', platform: 'Plateforme', delivery: 'Livraison', opened: 'Ouvert le', pushStatus: 'Statut push', lastActivity: 'Dernière activité', actions: 'Actions' },
      facts: { application: 'Application', status: 'État', future: 'Future', sentAt: 'Envoyée le', createdAt: 'Créée le', scheduledFor: 'Demandée pour', effective: 'Effective', targetedDevices: 'Devices ciblés' },
      labels: { scheduled: 'Planifiée', shifted: 'Décalée', yes: 'Oui', no: 'Non', notYet: 'Pas encore', immediate: 'Immédiat', notDelivered: 'non livrée' },
      actions: { view: 'Voir le détail' },
      dialog: { title: 'Modifier la notification', message: 'Message', newDate: 'Nouvelle date', save: 'Enregistrer', saving: 'Enregistrement...' },
      errors: { invalidId: 'Identifiant notification invalide.' },
    },
    adminStatus: {
      back: 'Retour au tableau de bord',
      eyebrow: 'Administration',
      title: 'État du backend',
      description: 'Supervision des services backend et des métriques clés.',
      refresh: 'Rafraîchir',
      loading: 'Chargement de l\'état du backend...',
      error: 'Impossible de charger l\'état du backend.',
      overallTitle: 'État global',
      overallStatus: { ok: 'Opérationnel', degraded: 'Dégradé', unknown: 'Inconnu' },
      djangoAdmin: 'Ouvrir l\'admin Django',
      checksTitle: 'Contrôles',
      checkStatus: { ok: 'ok', degraded: 'dégradé', error: 'erreur', unknown: 'inconnu' },
      checks: { database: 'Base de données', celery_broker: 'Broker Celery', celery_workers: 'Workers Celery', exchange: 'Exchange' },
      noDetail: 'Aucun détail.',
      metricsTitle: 'Métriques',
      metrics: {
        applications: 'Applications',
        applicationsActive: 'Actives',
        devices: 'Devices',
        notifications: 'Notifications',
        processingStuck: 'Notifications bloquées',
        none: 'Aucune métrique disponible.',
      },
    },
  },
  nl: {
    applications: { title: 'Beheer van applicaties', total: 'Totaal', active: 'Actief', refresh: 'Vernieuwen', add: 'Toevoegen', empty: 'Geen applicaties voor dit account.', loading: 'Applicatie laden...', noDescription: 'Geen beschrijving.', statuses: { active: 'actief', inactive: 'inactief' }, table: { name: 'Naam', description: 'Beschrijving', prefix: 'Prefix', status: 'Status', createdAt: 'Aangemaakt op', actions: 'Acties' }, actions: { view: 'Details bekijken', edit: 'Bewerken', activate: 'Activeren', deactivate: 'Deactiveren', regenerate: 'Token vernieuwen', revoke: 'Token intrekken', delete: 'Verwijderen', qrCode: 'QR-code' }, qr: { title: 'QR-code van het token', scanHint: 'Scan deze QR-code met de mobiele PushIT-app om een toestel te koppelen.', tokenOnce: 'Het token is slechts eenmaal zichtbaar. Vernieuw het om de QR-code te tonen (reeds gekoppelde toestellen blijven werken).', regenerate: 'Vernieuwen en tonen', error: 'Kan de QR-code niet genereren.', loading: 'QR-code genereren…', copyToken: 'Token kopiëren', copied: 'Token naar klembord gekopieerd.', copyFailed: 'Kan het token niet kopiëren.', downloadQr: 'QR-code downloaden', downloadToken: 'Token downloaden', saveNotice: '⚠️ Dit token wordt slechts één keer getoond: kopieer of download het nu en bewaar het veilig.' }, logo: { label: 'Logo', none: 'Geen logo', remove: 'Logo verwijderen', choose: 'Kies een afbeelding', hint: 'Sleep een afbeelding hierheen (PNG/JPG, max 2 MB).', cropHint: 'Versleep en zoom om in de cirkel te kaderen.', zoomIn: 'Inzoomen', zoomOut: 'Uitzoomen', apply: 'Toepassen', change: 'Andere afbeelding' }, dialog: { createTitle: 'Applicatie aanmaken', editTitle: 'Applicatie bewerken', create: 'Applicatie aanmaken', creating: 'Bezig met aanmaken...', save: 'Opslaan', saving: 'Bezig met opslaan...' }, alerts: { created: 'Applicatie aangemaakt. Open de QR-code om het token te bekijken, kopiëren of downloaden.', updated: 'Applicatie {name} bijgewerkt.', activated: 'Applicatie succesvol geactiveerd.', deactivated: 'Applicatie succesvol gedeactiveerd.', regenerated: 'Nieuw token gegenereerd. Open de QR-code om het te bekijken, kopiëren of downloaden.', revoked: 'Het token van deze applicatie werd ingetrokken.', deleted: 'Applicatie {name} verwijderd.' }, errors: { create: 'Kan de applicatie niet aanmaken.', toggle: 'Kan de status van de applicatie niet bijwerken.', regenerate: 'Kan het token niet vernieuwen.', revoke: 'Kan het token niet intrekken.', invalidId: 'Ongeldige applicatie-id.' }, confirmDelete: 'Applicatie "{name}" verwijderen?' },
    devices: { title: 'Inventaris en koppeling van devices', countLabel: 'devices', refresh: 'Vernieuwen', add: 'Toevoegen', empty: 'Geen gekoppelde devices voor dit account.', loading: 'Devices laden...', none: 'geen', never: 'Nooit', table: { name: 'Naam', platform: 'Platform', token: 'Token', applications: 'Applicaties', lastActivity: 'Laatste activiteit', actions: 'Acties', prefix: 'Prefix', status: 'Status', createdAt: 'Aangemaakt op' }, actions: { view: 'Details bekijken', edit: 'Bewerken', delete: 'Verwijderen', useLatestToken: 'Laatste gegenereerde token gebruiken', link: 'Device koppelen', linking: 'Bezig met koppelen...', save: 'Opslaan', saving: 'Bezig met opslaan...' }, dialog: { createTitle: 'Een device koppelen', editTitle: 'Device bewerken' }, createForm: { appToken: 'X-App-Token', appTokenPlaceholder: 'Plak hier het ruwe token', deviceName: 'Naam van het device', deviceNamePlaceholder: 'Marie iPhone', platform: 'Platform', pushToken: 'Push token', pushTokenPlaceholder: 'ExponentPushToken...' }, alerts: { updated: 'Device succesvol bijgewerkt.', deleted: 'Device verwijderd.', linked: 'Device {deviceId} gekoppeld aan applicatie {applicationId}.' }, errors: { missingAppToken: 'Vul een X-App-Token in om een device te koppelen.', invalidId: 'Ongeldige device-id.', loading: 'Device laden...' }, confirmDelete: 'Device "{name}" verwijderen?' },
    notifications: { title: 'Gebruikersnotificaties', history: 'Historiek', future: 'Toekomstig', shifted: 'Verschoven', refresh: 'Vernieuwen', add: 'Toevoegen', empty: 'Geen notificaties voor deze filters.', loading: 'Notificaties laden...', immediate: 'onmiddellijk', scheduledSubtext: 'Gepland', filters: { application: 'Applicatie', device: 'Device', status: 'Status', from: 'Effectief vanaf', to: 'Effectief tot', allApps: 'Alle', allDevices: 'Alle', allStatuses: 'Alle', apply: 'Toepassen', reset: 'Resetten' }, table: { name: 'Naam', application: 'Applicatie', message: 'Bericht', status: 'Status', effective: 'Effectief', actions: 'Acties' }, actions: { view: 'Details bekijken', send: 'Versturen', resend: 'Opnieuw versturen', edit: 'Bewerken', delete: 'Verwijderen' }, dialog: { createTitle: 'Notificatie aanmaken', editTitle: 'Toekomstige notificatie bewerken', create: 'Notificatie aanmaken', creating: 'Bezig met aanmaken...', save: 'Opslaan', saving: 'Bezig met opslaan...' }, form: { application: 'Applicatie', applicationPlaceholder: 'Kiezen...', devices: 'Doeldevices', devicesPlaceholder: 'Kies een of meerdere devices', devicesHelp: 'Alleen actieve devices gekoppeld aan de geselecteerde applicatie worden voorgesteld.', title: 'Titel', titlePlaceholder: 'Weekendpromo', message: 'Bericht', messagePlaceholder: 'Je pushbericht', schedule: 'Optionele planning', newDate: 'Nieuwe datum' }, alerts: { createdImmediate: 'Onmiddellijke notificatie aangemaakt.', sentImmediate: 'Notificatie verzonden.', createdScheduled: 'Geplande notificatie aangemaakt.', updated: 'Toekomstige notificatie bijgewerkt.', deleted: 'Toekomstige notificatie "{title}" verwijderd.', queued: 'Notificatie {notificationId} in wachtrij geplaatst: {taskId}.' }, confirmDelete: 'Toekomstige notificatie "{title}" verwijderen?', statusLabels: { draft: 'concept', scheduled: 'gepland', queued: 'in wachtrij', processing: 'bezig', sent: 'verzonden', partial: 'gedeeltelijk', failed: 'mislukt', no_target: 'zonder doel', shifted: 'verschoven' }, typeLabels: { future: 'Toekomstig', history: 'Historiek' }, errors: { invalidId: 'Ongeldige notificatie-id.', loading: 'Notificatie laden...' }, validation: { title: 'Ontbrekende velden', detail: 'Vul alle verplichte velden in (applicatie, toestellen, titel en bericht).' } },
    quietPeriods: { title: 'Beheer van stille vensters', refresh: 'Vernieuwen', add: 'Toevoegen', empty: 'Geen stille periodes geconfigureerd.', loading: 'Stille periodes laden...', targetNone: 'Geen doel', targetUnknownApplication: 'Onbekende applicatie', targetUnknownDevice: 'Onbekend device', missingTargets: 'Geen applicatie of device beschikbaar om een stille periode aan te maken.', missingParent: 'Selecteer een geldig doel voor je een stille periode aanmaakt.', table: { target: 'Doel', name: 'Naam', type: 'Type', rule: 'Regel', status: 'Status', actions: 'Acties' }, dialog: { createTitle: 'Nieuwe stille periode', editTitle: 'Stille periode bewerken', create: 'Periode aanmaken', update: 'Bijwerken', saving: 'Bezig met opslaan...' }, scopeLabels: { application: 'Applicatie', device: 'Device' }, typeLabels: { once: 'Eenmalig', recurring: 'Terugkerend', badgeOnce: 'eenmalig', badgeRecurring: 'terugkerend' }, statusLabels: { active: 'actief', inactive: 'inactief' }, form: { target: 'Doel', device: 'Device', application: 'Applicatie', selectPlaceholder: 'Kiezen...', name: 'Naam', namePlaceholder: 'Marketingnacht', type: 'Type', recurrenceDays: 'Herhalingsdagen', startTime: 'Startuur', endTime: 'Einduur', startAt: 'Start', endAt: 'Einde', active: 'Periode actief' }, weekdays: ['Ma', 'Di', 'Wo', 'Do', 'Vr', 'Za', 'Zo'], defaultNames: { application: 'Stilte applicatie', device: 'Stilte device' }, alerts: { created: 'Stille periode aangemaakt.', updated: 'Stille periode bijgewerkt.', deleted: 'Stille periode "{name}" verwijderd.' }, actions: { edit: 'Bewerken', delete: 'Verwijderen' }, confirmDelete: 'Stille periode "{name}" verwijderen?', validation: { onceRequired: 'Een eenmalige periode vereist een start- en einddatum.', recurringRequired: 'Een terugkerende periode vereist dagen en een tijdsvenster.', required: 'Dit veld is verplicht.', selectOneDay: 'Selecteer minstens een dag.', endAfterStart: 'Het einde van de stille periode moet na het begin liggen.', differentEndTime: 'De eindtijd moet verschillen van de begintijd.' } },
    applicationDetail: {
      back: 'Terug naar applicaties',
      eyebrow: 'Applicatie',
      fallbackTitle: 'Applicatiedetail',
      retry: 'Opnieuw proberen',
      editTooltip: 'Applicatie bewerken',
      loading: 'Applicatie laden...',
      descriptionTitle: 'Beschrijving',
      descriptionEmpty: 'Geen beschrijving beschikbaar voor deze applicatie.',
      inboundEmailTitle: 'E-mailadres voor notificaties',
      inboundEmailLabel: 'E-mailadres',
      inboundEmailCopy: 'Adres kopieren',
      inboundEmailCopied: 'E-mailadres gekopieerd.',
      inboundEmailCopyFailed: 'Kan het e-mailadres niet kopieren.',
      inboundEmailHelpTitle: 'Een notificatie via e-mail versturen',
      inboundEmailHelp: {
        intro: 'Stuur een e-mail naar dit adres om een notificatie voor deze applicatie aan te maken.',
        subject: 'Het onderwerp van de e-mail wordt de titel van de notificatie.',
        body: 'De tekstinhoud van de e-mail wordt het bericht.',
        schedule: 'Planning is mogelijk met [SEND_AT:ISO_DATETIME] in het onderwerp.',
        sender: 'De afzender moet het e-mailadres van de eigenaar van de applicatie zijn.',
      },
      devicesTitle: 'Gekoppelde devices',
      devicesEmpty: 'Geen devices gekoppeld aan deze applicatie.',
      notificationsTitle: 'Notificaties',
      notificationsEmpty: 'Geen notificaties gekoppeld aan deze applicatie.',
      quietPeriodsTitle: 'Stille periodes',
      quietPeriodsEmpty: 'Geen stille periodes gekoppeld aan deze applicatie.',
      statusTitle: 'Status',
      table: {
        name: 'Naam',
        platform: 'Platform',
        pushStatus: 'Pushstatus',
        lastActivity: 'Laatste activiteit',
        prefix: 'Prefix',
        status: 'Status',
        createdAt: 'Aangemaakt op',
        title: 'Titel',
        type: 'Type',
        effective: 'Effectief',
        actions: 'Acties',
      },
      facts: {
        id: 'ID',
        name: 'Naam',
        tokenPrefix: 'Tokenprefix',
        status: 'Status',
        lastUsed: 'Laatst gebruikt',
        revokedToken: 'Token ingetrokken',
        createdAt: 'Aangemaakt op',
      },
      statusLabels: {
        active: 'Actief',
        inactive: 'Inactief',
        never: 'Nooit',
        no: 'Nee',
        immediate: 'Onmiddellijk',
        once: 'eenmalig',
        recurring: 'terugkerend',
      },
      notificationTypes: { future: 'Toekomstig', history: 'Historiek' },
      actions: { view: 'Details bekijken' },
      dialog: { title: 'Applicatie bewerken', save: 'Opslaan', saving: 'Bezig met opslaan...' },
      logo: { label: 'Logo', none: 'Geen logo', remove: 'Logo verwijderen', updated: 'Logo bijgewerkt.', removed: 'Logo verwijderd.', choose: 'Kies een afbeelding', hint: 'Sleep een afbeelding hierheen (PNG/JPG, max 2 MB).', cropHint: 'Versleep en zoom om in de cirkel te kaderen.', zoomIn: 'Inzoomen', zoomOut: 'Uitzoomen', apply: 'Toepassen', change: 'Andere afbeelding' },
      regenerateEmail: {
        label: 'Inkomend e-mailadres',
        button: 'Adres opnieuw genereren',
        pending: 'Bezig met genereren...',
        hint: 'Genereert een nieuw willekeurig adres; het oude stopt met werken.',
        confirm: 'Het e-mailadres van "{name}" opnieuw genereren? Het huidige adres stopt onmiddellijk met werken.',
        success: 'Nieuw e-mailadres gegenereerd.',
        error: 'Kan het e-mailadres niet opnieuw genereren.',
      },
      aliasStatus: {
        title: 'Inkomende e-mailalias controleren',
        button: 'Alias controleren',
        pending: 'Bezig met controleren...',
        active: 'Alias actief',
        missing: 'Alias ontbreekt',
        missingHint: 'De alias bestaat niet op Exchange. Genereer het adres opnieuw of neem contact op met ops.',
        unavailable: 'Controle niet beschikbaar (Exchange niet geconfigureerd)',
        unverifiable: 'Kan niet controleren',
        error: 'Kan de alias niet controleren.',
      },
      errors: { invalidId: 'Ongeldige applicatie-id.', logo: 'Kan het logo niet bijwerken.' },
    },
    deviceDetail: { back: 'Terug naar devices', eyebrow: 'Device', fallbackTitle: 'Devicedetail', editTooltip: 'Device bewerken', loading: 'Device laden...', applicationsTitle: 'Gekoppelde applicaties', applicationsEmpty: 'Geen gekoppelde applicaties.', unlinkedTitle: 'Ontkoppelde applicaties', unlinkedOn: 'ontkoppeld op', unlinkedUnknownDate: 'datum onbekend', unlinkSources: { deviceButton: 'vanaf het toestel', inbox: 'vanuit de inbox', takeover: 'overgenomen door een ander account', unknown: 'onbekende bron' }, statusTitle: 'Status', table: { name: 'Naam', prefix: 'Prefix', status: 'Status', createdAt: 'Aangemaakt op', actions: 'Acties' }, facts: { id: 'ID', name: 'Naam', platform: 'Platform', tokenStatus: 'Tokenstatus', lastActivity: 'Laatste activiteit', createdAt: 'Aangemaakt op' }, labels: { never: 'Nooit', active: 'actief', inactive: 'inactief' }, actions: { view: 'Details bekijken' }, dialog: { title: 'Device bewerken', save: 'Opslaan', saving: 'Bezig met opslaan...' }, errors: { invalidId: 'Ongeldige device-id.' }, notifications: { title: 'Ontvangen notificaties', allApps: 'Alle applicaties', filterLabel: 'Filteren op applicatie', empty: 'Geen notificaties geleverd aan dit device.', unknown: 'onbekend', table: { title: 'Titel', application: 'Applicatie', delivery: 'Levering', sentAt: 'Verzonden op', actions: 'Acties' } } },
    notificationDetail: { back: 'Terug naar notificaties', eyebrow: 'Notificatie', fallbackTitle: 'Notificatiedetail', editTooltip: 'Notificatie bewerken', loading: 'Notificatie laden...', messageTitle: 'Bericht', devicesTitle: 'Doeldevices', devicesEmpty: 'Geen doeldevice gevonden voor deze notificatie.', statusTitle: 'Status', note: '`effective_scheduled_for` houdt alleen rekening met stille periodes op applicatieniveau. Deviceperiodes kunnen een delivery vertragen zonder deze datum te wijzigen.', table: { name: 'Naam', platform: 'Platform', delivery: 'Levering', opened: 'Geopend op', pushStatus: 'Pushstatus', lastActivity: 'Laatste activiteit', actions: 'Acties' }, facts: { application: 'Applicatie', status: 'Status', future: 'Toekomstig', sentAt: 'Verzonden op', createdAt: 'Aangemaakt op', scheduledFor: 'Gevraagd voor', effective: 'Effectief', targetedDevices: 'Doeldevices' }, labels: { scheduled: 'Gepland', shifted: 'Verschoven', yes: 'Ja', no: 'Nee', notYet: 'Nog niet', immediate: 'Onmiddellijk', notDelivered: 'niet geleverd' }, actions: { view: 'Details bekijken' }, dialog: { title: 'Notificatie bewerken', message: 'Bericht', newDate: 'Nieuwe datum', save: 'Opslaan', saving: 'Bezig met opslaan...' }, errors: { invalidId: 'Ongeldige notificatie-id.' } },
    adminStatus: {
      back: 'Terug naar dashboard',
      eyebrow: 'Beheer',
      title: 'Backendstatus',
      description: 'Monitoring van de backendservices en belangrijkste metrieken.',
      refresh: 'Vernieuwen',
      loading: 'Backendstatus laden...',
      error: 'Kan de backendstatus niet laden.',
      overallTitle: 'Algemene status',
      overallStatus: { ok: 'Operationeel', degraded: 'Verminderd', unknown: 'Onbekend' },
      djangoAdmin: 'Django-admin openen',
      checksTitle: 'Controles',
      checkStatus: { ok: 'ok', degraded: 'verminderd', error: 'fout', unknown: 'onbekend' },
      checks: { database: 'Database', celery_broker: 'Celery-broker', celery_workers: 'Celery-workers', exchange: 'Exchange' },
      noDetail: 'Geen details.',
      metricsTitle: 'Metrieken',
      metrics: {
        applications: 'Applicaties',
        applicationsActive: 'Actief',
        devices: 'Devices',
        notifications: 'Notificaties',
        processingStuck: 'Vastgelopen notificaties',
        none: 'Geen metrieken beschikbaar.',
      },
    },
  },
  en: {
    applications: { title: 'Application management', total: 'Total', active: 'Active', refresh: 'Refresh', add: 'Add', empty: 'No applications for this account.', loading: 'Loading application...', noDescription: 'No description.', statuses: { active: 'active', inactive: 'inactive' }, table: { name: 'Name', description: 'Description', prefix: 'Prefix', status: 'Status', createdAt: 'Created', actions: 'Actions' }, actions: { view: 'View details', edit: 'Edit', activate: 'Activate', deactivate: 'Deactivate', regenerate: 'Regenerate token', revoke: 'Revoke token', delete: 'Delete', qrCode: 'QR code' }, qr: { title: 'Token QR code', scanHint: 'Scan this QR code with the PushIT mobile app to link a device.', tokenOnce: 'The token is only shown once. Regenerate it to display its QR code (already-linked devices are not affected).', regenerate: 'Regenerate and show', error: 'Could not generate the QR code.', loading: 'Generating the QR code…', copyToken: 'Copy token', copied: 'Token copied to clipboard.', copyFailed: 'Could not copy the token.', downloadQr: 'Download QR code', downloadToken: 'Download token', saveNotice: '⚠️ This token is shown only once: copy or download it now and keep it somewhere safe.' }, logo: { label: 'Logo', none: 'No logo', remove: 'Remove logo', choose: 'Choose an image', hint: 'Drag and drop an image here (PNG/JPG, max 2 MB).', cropHint: 'Drag and zoom to frame inside the circle.', zoomIn: 'Zoom in', zoomOut: 'Zoom out', apply: 'Apply', change: 'Change image' }, dialog: { createTitle: 'Create application', editTitle: 'Edit application', create: 'Create application', creating: 'Creating...', save: 'Save', saving: 'Saving...' }, alerts: { created: 'Application created. Open the QR code to view, copy or download the token.', updated: 'Application {name} updated.', activated: 'Application activated successfully.', deactivated: 'Application deactivated successfully.', regenerated: 'New token generated. Open the QR code to view, copy or download it.', revoked: 'This application token was revoked.', deleted: 'Application {name} deleted.' }, errors: { create: 'Unable to create the application.', toggle: 'Unable to update the application state.', regenerate: 'Unable to regenerate the token.', revoke: 'Unable to revoke the token.', invalidId: 'Invalid application id.' }, confirmDelete: 'Delete application "{name}"?' },
    devices: { title: 'Device inventory and linking', countLabel: 'devices', refresh: 'Refresh', add: 'Add', empty: 'No linked devices for this account.', loading: 'Loading devices...', none: 'none', never: 'Never', table: { name: 'Name', platform: 'Platform', token: 'Token', applications: 'Applications', lastActivity: 'Last activity', actions: 'Actions', prefix: 'Prefix', status: 'Status', createdAt: 'Created' }, actions: { view: 'View details', edit: 'Edit', delete: 'Delete', useLatestToken: 'Use latest generated token', link: 'Link device', linking: 'Linking...', save: 'Save', saving: 'Saving...' }, dialog: { createTitle: 'Link a device', editTitle: 'Edit device' }, createForm: { appToken: 'X-App-Token', appTokenPlaceholder: 'Paste the raw token here', deviceName: 'Device name', deviceNamePlaceholder: 'Marie iPhone', platform: 'Platform', pushToken: 'Push token', pushTokenPlaceholder: 'ExponentPushToken...' }, alerts: { updated: 'Device updated successfully.', deleted: 'Device deleted.', linked: 'Device {deviceId} linked to application {applicationId}.' }, errors: { missingAppToken: 'Provide an X-App-Token to link a device.', invalidId: 'Invalid device id.', loading: 'Loading device...' }, confirmDelete: 'Delete device "{name}"?' },
    notifications: { title: 'User notifications', history: 'History', future: 'Future', shifted: 'Shifted', refresh: 'Refresh', add: 'Add', empty: 'No notifications for these filters.', loading: 'Loading notifications...', immediate: 'immediate', scheduledSubtext: 'Scheduled', filters: { application: 'Application', device: 'Device', status: 'Status', from: 'Effective from', to: 'Effective to', allApps: 'All', allDevices: 'All', allStatuses: 'All', apply: 'Apply', reset: 'Reset' }, table: { name: 'Name', application: 'Application', message: 'Message', status: 'Status', effective: 'Effective', actions: 'Actions' }, actions: { view: 'View details', send: 'Send', resend: 'Resend', edit: 'Edit', delete: 'Delete' }, dialog: { createTitle: 'Create notification', editTitle: 'Edit future notification', create: 'Create notification', creating: 'Creating...', save: 'Save', saving: 'Saving...' }, form: { application: 'Application', applicationPlaceholder: 'Choose...', devices: 'Target devices', devicesPlaceholder: 'Choose one or more devices', devicesHelp: 'Only active devices linked to the selected application are offered.', title: 'Title', titlePlaceholder: 'Weekend promo', message: 'Message', messagePlaceholder: 'Your push message', schedule: 'Optional scheduling', newDate: 'New date' }, alerts: { createdImmediate: 'Immediate notification created.', sentImmediate: 'Notification sent.', createdScheduled: 'Scheduled notification created.', updated: 'Future notification updated.', deleted: 'Future notification "{title}" deleted.', queued: 'Notification {notificationId} queued in task {taskId}.' }, confirmDelete: 'Delete future notification "{title}"?', statusLabels: { draft: 'draft', scheduled: 'scheduled', queued: 'queued', processing: 'processing', sent: 'sent', partial: 'partial', failed: 'failed', no_target: 'no target', shifted: 'shifted' }, typeLabels: { future: 'Future', history: 'History' }, errors: { invalidId: 'Invalid notification id.', loading: 'Loading notification...' }, validation: { title: 'Missing fields', detail: 'Please fill in all required fields (application, devices, title and message).' } },
    quietPeriods: { title: 'Quiet window management', refresh: 'Refresh', add: 'Add', empty: 'No quiet periods configured.', loading: 'Loading quiet periods...', targetNone: 'No target', targetUnknownApplication: 'Unknown application', targetUnknownDevice: 'Unknown device', missingTargets: 'No application or device available to create a quiet period.', missingParent: 'Select a valid target before creating a quiet period.', table: { target: 'Target', name: 'Name', type: 'Type', rule: 'Rule', status: 'Status', actions: 'Actions' }, dialog: { createTitle: 'New quiet period', editTitle: 'Edit quiet period', create: 'Create period', update: 'Update', saving: 'Saving...' }, scopeLabels: { application: 'Application', device: 'Device' }, typeLabels: { once: 'One-time', recurring: 'Recurring', badgeOnce: 'once', badgeRecurring: 'recurring' }, statusLabels: { active: 'active', inactive: 'inactive' }, form: { target: 'Target', device: 'Device', application: 'Application', selectPlaceholder: 'Choose...', name: 'Name', namePlaceholder: 'Marketing night', type: 'Type', recurrenceDays: 'Recurrence days', startTime: 'Start time', endTime: 'End time', startAt: 'Start', endAt: 'End', active: 'Active period' }, weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], defaultNames: { application: 'Application silence', device: 'Device silence' }, alerts: { created: 'Quiet period created.', updated: 'Quiet period updated.', deleted: 'Quiet period "{name}" deleted.' }, actions: { edit: 'Edit', delete: 'Delete' }, confirmDelete: 'Delete quiet period "{name}"?', validation: { onceRequired: 'A one-time period requires a start and end date.', recurringRequired: 'A recurring period requires days and a time range.', required: 'This field is required.', selectOneDay: 'Select at least one day.', endAfterStart: 'The end of the quiet period must be after the start.', differentEndTime: 'End time must differ from start time.' } },
    applicationDetail: {
      back: 'Back to applications',
      eyebrow: 'Application',
      fallbackTitle: 'Application detail',
      retry: 'Retry',
      editTooltip: 'Edit application',
      loading: 'Loading application...',
      descriptionTitle: 'Description',
      descriptionEmpty: 'No description available for this application.',
      inboundEmailTitle: 'Notification email address',
      inboundEmailLabel: 'Email address',
      inboundEmailCopy: 'Copy address',
      inboundEmailCopied: 'Email address copied.',
      inboundEmailCopyFailed: 'Unable to copy the email address.',
      inboundEmailHelpTitle: 'Send a notification by email',
      inboundEmailHelp: {
        intro: 'Send an email to this address to create a notification for this application.',
        subject: 'The email subject becomes the notification title.',
        body: 'The plain text email content becomes the message.',
        schedule: 'Scheduling is possible with [SEND_AT:ISO_DATETIME] in the subject.',
        sender: 'The sender must be the application owner email address.',
      },
      devicesTitle: 'Linked devices',
      devicesEmpty: 'No devices linked to this application.',
      notificationsTitle: 'Notifications',
      notificationsEmpty: 'No notifications linked to this application.',
      quietPeriodsTitle: 'Quiet periods',
      quietPeriodsEmpty: 'No quiet periods linked to this application.',
      statusTitle: 'Status',
      table: {
        name: 'Name',
        platform: 'Platform',
        pushStatus: 'Push status',
        lastActivity: 'Last activity',
        prefix: 'Prefix',
        status: 'Status',
        createdAt: 'Created',
        title: 'Title',
        type: 'Type',
        effective: 'Effective',
        actions: 'Actions',
      },
      facts: {
        id: 'ID',
        name: 'Name',
        tokenPrefix: 'Token prefix',
        status: 'Status',
        lastUsed: 'Last used',
        revokedToken: 'Revoked token',
        createdAt: 'Created',
      },
      statusLabels: {
        active: 'Active',
        inactive: 'Inactive',
        never: 'Never',
        no: 'No',
        immediate: 'Immediate',
        once: 'once',
        recurring: 'recurring',
      },
      notificationTypes: { future: 'Future', history: 'History' },
      actions: { view: 'View details' },
      dialog: { title: 'Edit application', save: 'Save', saving: 'Saving...' },
      logo: { label: 'Logo', none: 'No logo', remove: 'Remove logo', updated: 'Logo updated.', removed: 'Logo removed.', choose: 'Choose an image', hint: 'Drag and drop an image here (PNG/JPG, max 2 MB).', cropHint: 'Drag and zoom to frame inside the circle.', zoomIn: 'Zoom in', zoomOut: 'Zoom out', apply: 'Apply', change: 'Change image' },
      regenerateEmail: {
        label: 'Inbound email address',
        button: 'Regenerate address',
        pending: 'Regenerating...',
        hint: 'Generates a new random address; the old one stops working.',
        confirm: 'Regenerate the email address of "{name}"? The current address will immediately stop working.',
        success: 'New email address generated.',
        error: 'Unable to regenerate the email address.',
      },
      aliasStatus: {
        title: 'Verify inbound email alias',
        button: 'Verify alias',
        pending: 'Verifying...',
        active: 'Alias active',
        missing: 'Alias missing',
        missingHint: 'The alias does not exist on Exchange. Regenerate the address or contact ops.',
        unavailable: 'Verification unavailable (Exchange not configured)',
        unverifiable: 'Unable to verify',
        error: 'Unable to verify the alias.',
      },
      errors: { invalidId: 'Invalid application id.', logo: 'Unable to update the logo.' },
    },
    deviceDetail: { back: 'Back to devices', eyebrow: 'Device', fallbackTitle: 'Device detail', editTooltip: 'Edit device', loading: 'Loading device...', applicationsTitle: 'Linked applications', applicationsEmpty: 'No linked applications.', unlinkedTitle: 'Unlinked applications', unlinkedOn: 'unlinked on', unlinkedUnknownDate: 'unknown date', unlinkSources: { deviceButton: 'from the device', inbox: 'from the inbox', takeover: 'taken over by another account', unknown: 'unknown source' }, statusTitle: 'Status', table: { name: 'Name', prefix: 'Prefix', status: 'Status', createdAt: 'Created', actions: 'Actions' }, facts: { id: 'ID', name: 'Name', platform: 'Platform', tokenStatus: 'Token status', lastActivity: 'Last activity', createdAt: 'Created' }, labels: { never: 'Never', active: 'active', inactive: 'inactive' }, actions: { view: 'View details' }, dialog: { title: 'Edit device', save: 'Save', saving: 'Saving...' }, errors: { invalidId: 'Invalid device id.' }, notifications: { title: 'Received notifications', allApps: 'All applications', filterLabel: 'Filter by application', empty: 'No notifications delivered to this device.', unknown: 'unknown', table: { title: 'Title', application: 'Application', delivery: 'Delivery', sentAt: 'Sent at', actions: 'Actions' } } },
    notificationDetail: { back: 'Back to notifications', eyebrow: 'Notification', fallbackTitle: 'Notification detail', editTooltip: 'Edit notification', loading: 'Loading notification...', messageTitle: 'Message', devicesTitle: 'Target devices', devicesEmpty: 'No target device resolved for this notification.', statusTitle: 'Status', note: '`effective_scheduled_for` only reflects application quiet periods. Device quiet periods may delay a delivery without changing this date.', table: { name: 'Name', platform: 'Platform', delivery: 'Delivery', opened: 'Opened at', pushStatus: 'Push status', lastActivity: 'Last activity', actions: 'Actions' }, facts: { application: 'Application', status: 'Status', future: 'Future', sentAt: 'Sent at', createdAt: 'Created', scheduledFor: 'Requested for', effective: 'Effective', targetedDevices: 'Target devices' }, labels: { scheduled: 'Scheduled', shifted: 'Shifted', yes: 'Yes', no: 'No', notYet: 'Not yet', immediate: 'Immediate', notDelivered: 'not delivered' }, actions: { view: 'View details' }, dialog: { title: 'Edit notification', message: 'Message', newDate: 'New date', save: 'Save', saving: 'Saving...' }, errors: { invalidId: 'Invalid notification id.' } },
    adminStatus: {
      back: 'Back to dashboard',
      eyebrow: 'Administration',
      title: 'Backend status',
      description: 'Monitoring of the backend services and key metrics.',
      refresh: 'Refresh',
      loading: 'Loading backend status...',
      error: 'Unable to load the backend status.',
      overallTitle: 'Overall status',
      overallStatus: { ok: 'Operational', degraded: 'Degraded', unknown: 'Unknown' },
      djangoAdmin: 'Open Django admin',
      checksTitle: 'Checks',
      checkStatus: { ok: 'ok', degraded: 'degraded', error: 'error', unknown: 'unknown' },
      checks: { database: 'Database', celery_broker: 'Celery broker', celery_workers: 'Celery workers', exchange: 'Exchange' },
      noDetail: 'No detail.',
      metricsTitle: 'Metrics',
      metrics: {
        applications: 'Applications',
        applicationsActive: 'Active',
        devices: 'Devices',
        notifications: 'Notifications',
        processingStuck: 'Stuck notifications',
        none: 'No metrics available.',
      },
    },
  },
} as const;

@Injectable({ providedIn: 'root' })
export class ConsoleCopyService {
  private readonly i18n = inject(PublicI18nService);

  readonly current = computed(
    () => CONSOLE_COPY[this.i18n.language()],
  );
}
