#!/usr/bin/env bash
# =============================================================================
# PushIT frontend — Fetch runtime config from AWS SSM into a nginx snippet.
#
# Lancé par pushit-frontend-runtime-fetch.service (oneshot) au boot, et par
# deploy.sh à chaque déploiement. Lit /pushit-frontend/prod/* (eu-west-1) avec
# le rôle d'instance EC2 (l'unité blanke AWS_*_FILE pour éviter que les clés
# certbot-route53 de root masquent le rôle) et écrit un snippet nginx
# `set $pushit_* "...";` que le vhost inclut puis injecte dans index.html.
#
# La config frontend est PUBLIQUE (servie au navigateur) → que des String SSM,
# jamais de secret. Garde-fous : refuse les valeurs avec newline interne, écrit
# atomiquement (0644 root), idempotent (pas de reload si inchangé), valide
# `nginx -t` avant de recharger.
# =============================================================================
set -euo pipefail

SSM_PREFIX="${PUSHIT_FRONTEND_SSM_PREFIX:-/pushit-frontend/prod}"
AWS_REGION="${AWS_REGION:-eu-west-1}"
OUT_FILE="${PUSHIT_FRONTEND_RUNTIME_FILE:-/etc/nginx/snippets/pushit-frontend-runtime.conf}"

echo "[frontend-runtime] prefix=$SSM_PREFIX region=$AWS_REGION out=$OUT_FILE"

RAW_FILE="$(mktemp)"
TMP_FILE="$(mktemp)"
trap 'rm -f "$RAW_FILE" "$TMP_FILE"' EXIT

# Fetch raw JSON to a file first. If aws errors (IAM/IMDS/network), set -e stops
# here and the previous $OUT_FILE is left untouched.
aws ssm get-parameters-by-path \
    --path "$SSM_PREFIX" \
    --recursive \
    --region "$AWS_REGION" \
    --output json > "$RAW_FILE"

# Parse JSON -> nginx `set` directives. Le programme est lu depuis le heredoc
# (python3 -), les données depuis un FICHIER passé en argument : pas de conflit
# "programme sur stdin" vs "données sur stdin". Clés absentes -> défaut.
python3 - "$SSM_PREFIX" "$TMP_FILE" "$RAW_FILE" <<'PY'
import json, sys

prefix, out_path, raw_path = sys.argv[1], sys.argv[2], sys.argv[3]
with open(raw_path) as fh:
    params = json.load(fh).get("Parameters", [])

# Defaults appliqués pour toute clé absente de SSM.
values = {
    "API_BASE_URL": "",
    "SENTRY_DSN": "",
    "SENTRY_ENV": "production",
    "SENTRY_RELEASE": "",
    "FEATURES": "{}",
}

for p in params:
    key = p["Name"][len(prefix):].lstrip("/")
    # Tolère un CR/LF de fin (artefact CRLF d'un .env édité sous Windows) mais
    # rejette toute newline interne (corromprait la directive nginx `set`).
    value = p["Value"].strip("\r\n")
    if "\n" in value or "\r" in value:
        sys.stderr.write(f"ERROR: value for {key} contains an internal newline; refusing.\n")
        sys.exit(1)
    if key in values:
        values[key] = value

# FEATURES doit être un JSON valide, sinon on retombe sur {} pour ne pas casser
# la page. Le sub_filter du vhost injecte la variable SANS guillemets dans le
# <script> (window.__PUSHIT_FEATURES=$pushit_features → littéral objet JS), MAIS
# la directive nginx `set` ci-dessous DOIT être quotée : un `{}` nu serait lu
# comme un bloc nginx ("set is not terminated by ;"). nginx retire les guillemets
# en stockant la variable, donc la valeur reste le JSON brut. On échappe les "
# internes (nginx gère \" dans les chaînes quotées) pour les vrais objets JSON.
features = values["FEATURES"].strip() or "{}"
try:
    json.loads(features)
except ValueError:
    sys.stderr.write(f"WARN: FEATURES is not valid JSON ({features!r}); using {{}}.\n")
    features = "{}"
features_nginx = features.replace("\\", "\\\\").replace('"', '\\"')

lines = [
    "# AUTO-GENERATED by deploy/fetch-frontend-runtime-from-ssm.sh",
    f"# Source of truth: AWS SSM {prefix}/* (region from the unit). Manual edits",
    "# are overwritten on the next service restart / deploy.",
    f'set $pushit_api_base       "{values["API_BASE_URL"]}";',
    f'set $pushit_sentry_dsn     "{values["SENTRY_DSN"]}";',
    f'set $pushit_sentry_env     "{values["SENTRY_ENV"]}";',
    f'set $pushit_sentry_release "{values["SENTRY_RELEASE"]}";',
    f'set $pushit_features       "{features_nginx}";',
]
with open(out_path, "w") as fh:
    fh.write("\n".join(lines) + "\n")
PY

# Idempotence : rien à faire si le snippet est identique (évite un reload nginx).
if [ -f "$OUT_FILE" ] && cmp -s "$TMP_FILE" "$OUT_FILE"; then
    echo "[frontend-runtime] $OUT_FILE unchanged — no reload needed"
    exit 0
fi

mkdir -p "$(dirname "$OUT_FILE")"
install -m 0644 -o root -g root "$TMP_FILE" "$OUT_FILE"
echo "[frontend-runtime] $OUT_FILE updated"

# Garde : valide la config complète (vhost + snippet) avant de recharger. Si KO,
# on n'effectue pas le reload (le master tourne encore sur l'ancienne conf valide).
if ! nginx -t; then
    echo "ERROR: nginx -t failed after writing $OUT_FILE — skipping reload" >&2
    exit 3
fi

systemctl reload nginx
echo "[frontend-runtime] nginx reloaded"
